# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Sat Oct 22 18:18:52 2022)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/temp.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Tue Nov 15 16:51:22 2022)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled0.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled1.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec4.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/modul1.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec4.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec4.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec1.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled6.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec1.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec1.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runcell(0, 'C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec1.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec1.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runcell(0, 'C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runcell(0, 'C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Wed Nov 16 21:58:27 2022)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Thu Nov 17 17:36:02 2022)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled0.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork2py.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork2py.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork2py.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork2py.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3_2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec4.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Sat Nov 19 10:03:47 2022)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec1.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/examWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3_2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec4.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Sun Nov 20 12:06:31 2022)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/classWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/classWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/classWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec4.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/classWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/classWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec4.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/classWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Mon Nov 21 12:03:49 2022)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3_2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3_2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Sat Dec 31 19:36:30 2022)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec6.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Wed Jan  4 13:22:27 2023)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled0.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/appWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec6.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/appWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Wed Jan  4 17:49:08 2023)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec6.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/appWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec6.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/appWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec6.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/appWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec6.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec7.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Fri Jan 13 12:07:04 2023)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec7.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/appWork.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec7.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec8.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec7.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Sun Jan 15 09:40:09 2023)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled0.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec5.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled0.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec5.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec5.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExpectOdevi.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec6.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec8.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec8.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/untitled3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/uyarıOdevi.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/uyarıOdevi.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExpectOdevi.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExpectOdevi.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/uyarıOdevi.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec7.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec8.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec3_2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')

## ---(Mon Jan 16 14:32:05 2023)---
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec8.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec7.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec5.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/tryExcept2.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec5.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')
runfile('C:/Users/Simge SEVİNCER/.spyder-py3/GPLec9.py', wdir='C:/Users/Simge SEVİNCER/.spyder-py3')